version: "3.7"

services:
  mongo:
    container_name: mongo_latest__compose
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - learning_docker_network__compose
  redis:
    container_name: redis_alpine__compose
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - learning_docker_network__compose
  learning_docker:
    container_name: learning-docker_golang-container__compose
    image: learning-docker:golang-container
    ports:
      - 8080:8080
    networks:
      - learning_docker_network__compose
    depends_on:
      - mongo
      - redis
    environment:
      - NAME=Dokcer

networks:
  learning_docker_network__compose:
    name: learning_docker_network__compose
